const task = [
    {
      id: 1,
      tarea: "Completar informe",
      prioridad: "Alta",
      completada: false,
      nroOrden: 3,
    },
    {
      id: 2,
      tarea: "Enviar correo electrónico",
      prioridad: "Media",
      completada: true,
      nroOrden: 3,
    },
    {
      id: 3,
      tarea: "Preparar presentación",
      prioridad: "Alta",
      completada: false,
      nroOrden: 3,
    },
    {
      id: 4,
      tarea: "Reunión con equipo",
      prioridad: "Baja",
      completada: false,
      nroOrden: 3,
    },
    {
      id: 5,
      tarea: "Completar informe",
      prioridad: "Alta",
      completada: false,
      nroOrden: 3,
    },
    {
      id: 6,
      tarea: "Enviar correo electrónico",
      prioridad: "Media",
      completada: true,
      nroOrden: 3,
    },
    {
      id: 7,
      tarea: "Preparar presentación",
      prioridad: "Alta",
      completada: false,
      nroOrden: 3,
    },
    {
      id: 8,
      tarea: "Reunión con equipo",
      prioridad: "Baja",
      completada: false,
      nroOrden: 3,
    },
    {
      id: 9,
      tarea: "Completar informe",
      prioridad: "Alta",
      completada: false,
      nroOrden: 3,
    },
    {
      id: 10,
      tarea: "Enviar correo electrónico",
      prioridad: "Media",
      completada: true,
      nroOrden: 3,
    },
    {
      id: 11,
      tarea: "Preparar presentación",
      prioridad: "Alta",
      completada: false,
      nroOrden: 3,
    },
    {
      id: 12,
      tarea: "Reunión con equipo",
      prioridad: "Baja",
      completada: false,
      nroOrden: 3,
    },
  ];
  export const data = [
    {
      id: 1,
      textSecondary: "oficina 1",
      content: task,
    },
    {
      id: 2,
      textSecondary: "oficina 2",
      content: task,
    },
    {
      id: 3,
      textSecondary: "oficina 3",
      content: task,
    },
  ];