export const btnOK = { backgroundColor: "#A5B381", border: "none", color: "white", borderRadius: 20, padding: "5px 20px", fontSize: 15, mt: 1, textAlign: 'center', display: "flex", alignItems: "center", justifyContent: "center" }
export const inputGestionar = { width: "100%", backgroundColor: "white", mt: 1 }
export const btnModificar = { backgroundColor: "#edef00", border: "none", color: "black", fontSize: 15, m: 1, borderRadius: 1 ,width: 40, height: 35 }
export const btnEliminar = { backgroundColor: "#ff4242", border: "none", color: "white", fontSize: 15, m: 1, borderRadius: 1 ,width: 40, height: 35 }
export const btnDetalle = {  backgroundColor:"#A1B5D8", border: "none", color: "black", fontSize: 15, m: 1, borderRadius: 1 ,  width: 40, height: 35}
export const boxBtnOk = { display: 'flex', alignItems: 'center', justifyContent: "end", m: 1 }
export const styleModal = { position: 'absolute', top: '50%', left: '50%', transform: 'translate(-50%, -50%)', width: 500, bgcolor: 'background.paper', border: '2px solid #000', boxShadow: 24, p: 4, }
export const btnEliminarModal = { backgroundColor: "#ff4242", border: "none", color: "white", fontSize: 15, m: 1, borderRadius: 1, padding: "5px 10px" }
export const btnCancelarModal = { backgroundColor: "#ff4242", border: "none", color: "white", fontSize: 17, m: 1, borderRadius: 1, padding: "5px 10px" }
export const btnOKGestionar = { backgroundColor: "#A5B381", border: "none", color: "white", borderRadius: 1, padding: "5px 20px", fontSize: 17, m: 1 }
export const selectGestionar = {width: 170, color: "white" }
export const inputCaracteristica = {width: 310,  backgroundColor: "white", mt:1 }
export const btnEliminarCaracteristica = { backgroundColor: "#ff4242", border: "none", color: "white", fontSize: 9, m: 1, borderRadius: 10 ,width: 35, height: 35 }
export const btnAgregarCaracteristica = { backgroundColor: "#649557", border: "none", color: "white", fontSize: 9, m: 1, borderRadius: 10 ,width: 35, height: 35 }
export const inputFiltro = { width: 250, backgroundColor: "white", mt: 1 }
export const btnClearFiltro = { backgroundColor: "white", border: "none", color: "black", fontSize: 17, m: 1, borderRadius: 1, padding: "5px 10px" }
export const btnGuardarBien  = { backgroundColor: "#A5B381", border: "none", color: "white", borderRadius: 1, padding: "5px 20px", fontSize: 18, m: 1 }
export const btnCambiarOficina = { backgroundColor: "#edef00", border: "none", color: "black", fontSize: 14, m: 1, borderRadius: 1 , height: 35 }
export const btnOKFactura = { backgroundColor: "#A5B381", border: "none", color: "white", borderRadius: 20, padding: "5px 20px", fontSize: 16, mt: 1, textAlign: 'center', display: "flex", alignItems: "center", justifyContent: "center" }
export const btnModificarFactura = { backgroundColor: "#edef00", border: "none", color: "black", borderRadius: 20, padding: "5px 20px", fontSize: 16, mt: 1, textAlign: 'center', display: "flex", alignItems: "center", justifyContent: "center"  }
export const selectDetalle = { width: 500, backgroundColor: "white", mt: 1 }
export const formAltaBien = { p:3, backgroundColor:"white" , border:1, borderRadius: 10 , }
export const btnSeleccionarDetalle = { backgroundColor: "#649557", border: "none", color: "white",  fontSize: 15,  borderRadius: 1 ,  width: 40, height: 35}
